pythondjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework.routers import DefaultRouter

from webapp import views
from api import viewsets

router = DefaultRouter()
router.register(r'api/parser', viewsets.ParserViewSet, base_name='count_keyword_on_site')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webapp/', views.HeaderKey.as_view(), name='webapp'),
    # path(r'^api/', include('rest_framework.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += router.urls

api/models.py
from django.db import models


class UrlModel(models.Model):
    url = models.URLField()

webapp/models.py
from django.db import models

# Create your models here.

webapp/forms.py
from django import forms


class UrlForm(forms.Form):
    BEAUTIFUFULSOUP = 1
    REGEX = 2
    CHOICES_METHOD = (
        (BEAUTIFUFULSOUP, 'BeautifulSoup'),
        (REGEX, 'Regex'),
    )

    ajax_url = forms.URLField(required=False)
    method = forms.ChoiceField(choices=CHOICES_METHOD)
    url = forms.URLField(required=True)

api/views.py
from django.shortcuts import render

# Create your views here.

webapp/views.py
import requests

from django.shortcuts import render
from django.views.generic import ListView

from webapp.forms import UrlForm
from lib.parse_request import ParseResponse


class HeaderKey(ListView):
    template_name = 'webapp/header_key/urls.html'
    form_class = UrlForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            cleaned_fields = form.cleaned_data
            response = requests.get(cleaned_fields['url'])
            parser = ParseResponse(response.content)
            if cleaned_fields['method'] == UrlForm.BEAUTIFUFULSOUP:
                context = parser.count_keyword_on_site()
            else:
                context = parser.count_keyword_on_site_regex()
        return render(
            request,
            self.template_name,
            {'context': context, 'form': form}
        )

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pl">
<head>
    <title>Contman Zadanie</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'js/JqueryProxy.js' %}"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>

<body>
    <section>
        {% block content %}{% endblock %}
    </section>
</body>
</html>

templates/webapp/header_key/urls.html
{% extends "base.html" %}

{% block content %}
<form action="." method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
    <a id="send-ajax" href="#">Send Ajax Request</a>
</form>

<section class="section_result">
    <h1>Statistic of amount keywords</h1>
    {% for k, v in context.items %}
    <p>{{ k }} - {{ v }}</p>
    {% endfor %}
</section>


<div class="modal fade" id="myModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Statistic of amount keywords</h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<button id="button" type="button" style="display:none" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Show result of ajax request
</button>

<script>
    $("#send-ajax").on('click', function(){
        data_url = $("#id_ajax_url").val();
        proxy = new AjaxProxy(data_url);
        proxy.get_kyeword_counter();
    })
</script>


{% endblock %}